Trigger_Framework/objects/Transaction_Log__c.object
<CustomObject>
    <description>This Object main objective is to store the Error if there is any while processing the server request.</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Trigger/Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <label>Process Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-{0}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trigger_Framework/objects/Trigger_Setting__c.object
<CustomObject>
    <fields>
        <fullName>After_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked trigger will run in after delete context</inlineHelpText>
        <label>After Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Insert__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked trigger will run in after insert context</inlineHelpText>
        <label>After Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Undelete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked trigger will run in after undelete context</inlineHelpText>
        <label>After Undelete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>After_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked trigger will run in after update context</inlineHelpText>
        <label>After Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked trigger will run in before delete context</inlineHelpText>
        <label>Before Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Insert__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If Checked trigger will run in before insert context</inlineHelpText>
        <label>Before Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Before_Update__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If Checked trigger will run in before update context</inlineHelpText>
        <label>Before Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prevent_Recursion__c</fullName>
        <inlineHelpText>Please enter the fields API name with comma separated to prevent the recursion.</inlineHelpText>
        <label>Prevent Recursion</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Trigger Setting</label>
    <nameField>
        <displayFormat>TS - {00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trigger Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trigger_Framework/classes/TriggerDispatcherTest.cls
@isTest
private with sharing class TriggerDispatcherTest{
    @testSetup
    public static void setupTestData(){
        /* Insert Trigger Setting Object */
        Trigger_Setting__c triggerSetting = new Trigger_Setting__c(
            After_Delete__c = true, After_Insert__c = true, After_Undelete__c = true,
            After_Update__c = true, Before_Delete__c = true, Before_Insert__c = true,
            Before_Update__c = true, Object_Name__c = 'Account', Prevent_Recursion__c='Name,AccountNumber'    
        );
        insert triggerSetting;
        Trigger_Setting__c triggerSetting1 = new Trigger_Setting__c(
            After_Delete__c = true, After_Insert__c = true, After_Undelete__c = true,
            After_Update__c = true, Before_Delete__c = true, Before_Insert__c = true,
            Before_Update__c = true, Object_Name__c = 'TransactionLog'    
        );
        insert triggerSetting1;
        
        System.assertNotEquals(triggerSetting.Id, null);
        
        /* Insert 500 Accounts into the System so that we can test the Framework 
           For the bulk records
        */
        List<Account> accountList = new List<Account>();
        For(Integer i = 0; i<501; i++){
            Account acc = new Account(
                Name ='Test Frame work '+i,
                Industry = 'Banking'
            );
            accountList.add(acc);
        }
        
        insert accountList;
        
        List<Transaction_Log__c> transactionLogList = new List<Transaction_Log__c>();
        For(Integer i = 0; i<501; i++){    
            Transaction_Log__c tlog = new Transaction_Log__c(
                Class_Name__c ='TransactionLogTriggerHandler' ,
                Process_Name__c = 'TransactionLogTriggerHandler'
            );
            transactionLogList.add(tlog);
        }
        
        insert transactionLogList;
        
    }
    
    static testMethod void beforeContextTest(){
        List<Account> accountList = new List<Account>([Select Id, Name From Account LIMIT 205]);
        for(Account acc : accountList){
            acc.Name = acc.Name + 'SFDCPanther';
        }
        Test.startTest();
            List<Trigger_Setting__c> triggerSettingList = new List<Trigger_Setting__c>();
            triggerSettingList = [Select Id, Name,Object_Name__c From Trigger_Setting__c LIMIT 10];
            update triggerSettingList;
            update accountList;
            
            List<Transaction_Log__c> tLogList = new List<Transaction_Log__c>();
            tLogList = [Select Id, Name,Class_Name__c From Transaction_Log__c LIMIT 10];
            update tLogList;
            
            System.assertEquals(205, accountList.size());
        Test.stopTest();
    }
    
    static testMethod void afterContextTest(){
        List<Account> accountList = new List<Account>([Select Id, Name From Account LIMIT 100]);
        String Id = accountList[0].Id;
        Test.startTest();
            
            System.assertEquals(100, accountList.size());
            delete accountList;
            List<Account> accountListUnDelete = new List<Account>([SELECT Id, Name FROM Account LIMIT 100 ALL ROWS]);
            undelete accountListUnDelete;
            
            List<Transaction_Log__c> tLogList = new List<Transaction_Log__c>();
            tLogList = [Select Id, Name,Class_Name__c From Transaction_Log__c LIMIT 10];
            delete tLogList;
            
            List<Transaction_Log__c> tLogList1 = new List<Transaction_Log__c>();
            tLogList1 = [Select Id, Name,Class_Name__c From Transaction_Log__c LIMIT 10 ALL ROWS];
            //undelete tLogList1;
        Test.stopTest();
    }
    
    static testMethod void TransactionLogHandlerTest(){
        Test.StartTest();
            TransactionLogHandler.doHandleException(new System.DMLException(), 'AccountTriggerHandler');
            Integer i =1;
            System.assertEquals(1, I);
        Test.StopTest();
    }
}