Trigger_Framework_V1/objects/Transaction_Log__c.object
<CustomObject>
    <description>This Object main objective is to store the Error if there is any while processing the server request.</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Trigger/Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Log__c</fullName>
        <label>Error Log</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Exception_Time__c</fullName>
        <label>Exception Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <label>Process Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-{0}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trigger_Framework_V1/classes/TransactionLogHandler.cls
/*
    @Author : Amit Singh
    @BuiltDate : 21st March 2018
    @Description : This class will be called from the Trigger and then will redirect to the correct Handler
    @Company : sfdcpanther
*/

public with sharing class TransactionLogHandler{
    
    public static void doHandleException(System.Exception ex, String ProcessName){
        Transaction_Log__c tLog = new Transaction_Log__c();
        tLog.Exception_Time__c = System.now();
        tLog.Process_Name__c = ProcessName;
        tLog.Class_Name__c = ProcessName;
        tLog.Error_Log__c = ex.getStackTraceString() +'<br/>'+ ex.getLineNumber();
        
        insert tLog;
    }
}